### PR TITLE
finicky whiskers v2 update

### PR DESCRIPTION
**Pull request by flynnduism**
* ui updates
* play as slats or ninja
* new intro screen
* fix size to ipad air dimenions

Preview the changes: https://fw2.fermyon.app/index.html

### CODE REVIEW

**Comment by adamreese** [comment]
This is a massive PR. Is there anything specific you need reviewed?

**Comment by flynnduism** [comment]
> This is a massive PR. Is there anything specific you need reviewed?

It’s not changing functionality, just a game UI update - review wise to see it still works

**Review by adamreese — APPROVED** [review]
Only weirdness I found was 
image

**Comment by flynnduism** [comment]
Thanks @adamreese ! I'll follow up with a fix for this asap, but going to ship the game update for starters

**Pull request merged**
