### PR TITLE
introduce sessionv2, written in typescript, for compatibility with latest spin

### PR DESCRIPTION
**Pull request by endocrimes**
sessionv1 was written in Ruby, which is great for demo purposes, but
currently relies on an out of date wasi-libc that is unsupported by
latest spin.

Switch to the new Typescript version with full-wasi support (keeping the Ruby version in the hopes that it can be bought back to life).

### CODE REVIEW

**Review by vdice — COMMENTED** [review]
@endocrimes this PR looks great!  Thanks for updating the session module.

The only things I needed to [build and deploy from my fork](https://github.com/vdice/finicky-whiskers/actions/runs/10942654137/job/30380498614) were CI/CD changes.  Could you incorporate some or all?  I can help create follow-ups for any remaining items.

- Rebase off of main to get recent [build fix](https://github.com/fermyon/finicky-whiskers/pull/94)
- Need to install deps for sessionv2 in build.yml (eg https://github.com/vdice/finicky-whiskers/commit/5971a91de072168d06ecda6304d26ce7dee44835)
- Use relative build.yml, not pinned to main, to get update above (eg https://github.com/vdice/finicky-whiskers/commit/24097a88155a90030091160156f394dffbe0fb42) _Actually this change was only needed on my fork... but could be useful when working off of a branch and testing CI._
- Bump to spin v2.7.0 in CI (eg https://github.com/vdice/finicky-whiskers/commit/8b2cc938ed8dd32c8cf154b7d466aa602f08dd8d)
  - Otherwise I see the following when we `spin up` using the older 2.0.1 version to test the site: https://github.com/vdice/finicky-whiskers/actions/runs/10942569334/job/30379905619

**Comment by endocrimes** [comment]
@vdice oh thanks for looking into that! - I'll try and find some time to port them over early next week 😅

**Comment by vdice** [comment]
@endocrimes if you'd like, I'd be happy to rebase the branch and merge the updates mentioned/linked above.  Then we can get review(s) from others.

**Review by technosophos — APPROVED** [review]
Yup, this looks correct from the gameplay perspective.

**Comment by endocrimes** [comment]
@vdice if you have the time that would be awesome 💜

**Pull request merged**
